FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .

RUN node scripts/generateFooterData.js

CMD ["npm", "start"]

#docker run -it -p 3000:3000 IMAGE_ID
# docker run -it -p 8080:8080 -v /app/node_modules -v "/$(pwd)":/app 463dc0d7abeaa5