version: '3'
services:
  client:
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
     - '3050:80'
