version: '3'
services:
  web:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app


    