name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t emillos/simpleapp:latest -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true emillos/simpleapp:latest npm test
 
      - run: docker build -t emillos/simpleapp:latest .
 
      - run: docker push emillos/simpleapp:latest
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: simple-app-test
          environment_name: Simpleapptest-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-541850889889
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip