name: Deploy Emillos.com
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t emillos/emillos-client:latest -f ./Dockerfile .
      - run: docker run -e CI=true emillos/emillos-client:latest npm test
 
      - run: docker build -t emillos/emillos-client:latest .
 
      - run: docker push emillos/emillos-client:latest
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: emillos-application
          environment_name: Emillos-application-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-541850889889
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip